// Spike 4: does a generated union type of real module names actually fail
// tsc when a config references a name that doesn't exist — the same
// mechanism solarsql uses (a stale SQL statement fails to compile against
// last build's generated type until the build runs again)?
//
// Fixture (spike/fixtures/generated-union/): src/{app,features,shared}/ are
// the "real" modules. This script (1) scans that src/ the way archstrict's
// `init`/build step would, discovering module names from the filesystem —
// something tsc's own type system cannot do on its own, which is exactly
// why a generated file is the mechanism, not a purely structural generic
// (a generic constrained to `keyof typeof kinds` would validate the config
// against itself, but never catch a config that's gone stale relative to
// what's actually on disk after a directory was renamed or removed); (2)
// writes `archstrict.types.ts` with the discovered names as a union
// type; (3) runs tsc against a config that uses only real names (expect
// pass) and one with a typo'd name (expect fail); (4) reports both results.
import { execFileSync } from "node:child_process";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const FIXTURE = resolve("spike/fixtures/generated-union");

function discoverModuleNames(srcDir: string): string[] {
  return readdirSync(srcDir)
    .filter((name) => statSync(join(srcDir, name)).isDirectory())
    .sort();
}

function writeGeneratedUnion(moduleNames: string[]): void {
  const union = moduleNames.map((n) => JSON.stringify(n)).join(" | ");
  writeFileSync(
    join(FIXTURE, "archstrict.types.ts"),
    `// Generated by archstrict init. Do not edit.\n` +
      `export type ModuleName = ${union};\n`,
  );
}

// tsc -p checks every file matching the project's tsconfig, and this
// fixture's tsconfig has no "include", so it would pick up both
// archstrict.config.good.ts and archstrict.config.bad.ts together, which
// tests nothing (the bad one always fails the batch) — an artifact of this
// spike having two configs side by side to test both outcomes, not a
// property the real CLI needs: archstrict never runs tsc itself; it writes
// the generated file, and the project's own `tsc` is what fails or passes
// on it, exactly as the spec's "綴りは tsc が落とす" says. Point tsc at one
// config file at a time via a throwaway tsconfig that includes just it.
function tscOnOneConfig(configFileName: string): { exitCode: number; firstDiagnosticLine: string | undefined } {
  const oneOff = join(FIXTURE, "tsconfig.oneoff.json");
  writeFileSync(
    oneOff,
    JSON.stringify(
      {
        extends: "./tsconfig.json",
        include: [configFileName, "config-type.ts", "archstrict.types.ts"],
      },
      null,
      2,
    ),
  );
  try {
    execFileSync(
      "node",
      [resolve("node_modules/typescript/bin/tsc"), "--noEmit", "-p", oneOff],
      { encoding: "utf8", cwd: FIXTURE, stdio: "pipe" },
    );
    return { exitCode: 0, firstDiagnosticLine: undefined };
  } catch (e) {
    const err = e as { status?: number; stdout?: string };
    return {
      exitCode: err.status ?? 1,
      firstDiagnosticLine: err.stdout?.split("\n").find((line) => line.includes("error TS")),
    };
  }
}

function main(): void {
  const moduleNames = discoverModuleNames(join(FIXTURE, "src"));
  writeGeneratedUnion(moduleNames);

  const good = tscOnOneConfig("archstrict.config.good.ts");
  const bad = tscOnOneConfig("archstrict.config.bad.ts");

  console.log(
    JSON.stringify(
      {
        discoveredModules: moduleNames,
        goodConfig: { exitCode: good.exitCode, typechecks: good.exitCode === 0 },
        badConfig: {
          exitCode: bad.exitCode,
          typoCaughtByTsc: bad.exitCode !== 0,
          diagnostic: bad.firstDiagnosticLine,
        },
        verdict:
          good.exitCode === 0 && bad.exitCode !== 0
            ? "go: tsc accepts real module names and rejects a typo"
            : "no-go: see exit codes above",
      },
      null,
      2,
    ),
  );
}

main();
