// Responsibility: the `init` verb. Writes only the root
// archstrict.config.ts and the generated module-name union type; it does
// not create any per-module public-surface files. Idempotent: a second run
// regenerates archstrict.generated.ts (init's own file) but leaves an
// existing archstrict.config.ts untouched, so a hand-edited config is
// never overwritten.
// Boundary: file I/O and text generation only. Discovering modules is
// module-graph.ts's job; init reuses it rather than re-implementing
// directory scanning.
//
// The generated file carries its own self-contained `Config` type
// (specialized with the real `ModuleName` union), rather than the config
// importing a generic `Config<ModuleName>` from a package entry point:
// archstrict has no published package surface yet, and this project's own
// config shape is free to change as long as the properties it guarantees
// hold. This keeps `archstrict.config.ts` a one-import file that works
// whether or not archstrict is ever published, and matches spike 4's own
// fixture (a self-contained `Config<ModuleName>` beside the generated
// file, not a package import).
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildModuleGraph } from "../module-graph.js";

export type InitResult = {
  configPath: string;
  generatedPath: string;
  configWritten: boolean; // false when archstrict.config.ts already existed and was left alone
  moduleNames: string[];
};

// The flat preset, v0's only one: every module under the glob is the same
// kind, checked for a public surface and cycles only. `because` is
// mandatory even for a shipped preset's own rule.
const FLAT_BECAUSE =
  "flat preset: every module under the glob is one kind, checked for its public surface and cycles";

// The public-surface file name is not fixed by the tool — a project's own
// config names it. init does not try to detect an existing convention
// (a repository that already used a different name for this purpose would
// need to say so itself); it always writes this literal default, and a
// project free to rename its own surface file edits `surface` afterward.
const DEFAULT_SURFACE = "index.ts";

function generatedFileContents(moduleNames: string[]): string {
  const union = moduleNames.length > 0 ? moduleNames.map((n) => JSON.stringify(n)).join(" | ") : "never";
  return `// Generated by archstrict init. Do not edit.
// A stale name here means a module was added, removed, or renamed since
// the last init; run init again to regenerate.
export type ModuleName = ${union};

// configPath is added by the loader, not written here - a config file
// cannot know its own path.
export type Config = {
  modules: string;
  // The public-surface file name every module is checked against, e.g.
  // "index.ts". Not fixed by the tool - a project names its own.
  surface: string;
  kinds: Record<string, string>;
  layers?: readonly string[];
  deprecated?: readonly {
    from: ModuleName;
    to: ModuleName;
    count: number;
    because: string;
  }[];
  // Module names whose todo file may only shrink, never gain a new entry.
  // check reports any existing entry in one of these modules' todo as a
  // violation in its own right.
  strict?: readonly ModuleName[];
  because: string;
};
`;
}

function configFileContents(modulesGlob: string, surface: string): string {
  return `import type { Config } from "./archstrict.generated.js";

// Public surface convention: a module's ${surface} (named by \`surface\`
// below) is the only file other modules may import from it. An import
// that reaches any other file inside a module is a violation. A module
// with no ${surface} is entirely private - every import into it violates.
export default {
  modules: ${JSON.stringify(modulesGlob)},
  surface: ${JSON.stringify(surface)},
  kinds: { flat: ${JSON.stringify(modulesGlob)} },
  because: ${JSON.stringify(FLAT_BECAUSE)},
} satisfies Config;
`;
}

export function init(projectRoot: string, modulesGlob = "src/*", surface = DEFAULT_SURFACE): InitResult {
  const graph = buildModuleGraph({ projectRoot, modulesGlob, surface });
  const moduleNames = [...graph.modules.keys()].sort();

  const generatedPath = join(projectRoot, "archstrict.generated.ts");
  writeFileSync(generatedPath, generatedFileContents(moduleNames));

  const configPath = join(projectRoot, "archstrict.config.ts");
  const configWritten = !existsSync(configPath);
  if (configWritten) {
    writeFileSync(configPath, configFileContents(modulesGlob, surface));
  }

  return { configPath, generatedPath, configWritten, moduleNames };
}
