// Responsibility: the `init` verb. Writes only the root
// archstrict.config.ts and the generated module-name union type; it does
// not create any per-module public-surface files. Idempotent: a second run
// regenerates archstrict.types.ts (init's own file) but leaves an
// existing archstrict.config.ts untouched, so a hand-edited config is
// never overwritten.
// Boundary: file I/O and text generation only. Discovering modules is
// module-graph.ts's job; init reuses it rather than re-implementing
// directory scanning.
//
// The generated file carries its own self-contained `Config` type
// (specialized with the real `ModuleName` union), rather than the config
// importing a generic `Config<ModuleName>` from a package entry point:
// archstrict has no published package surface yet, and this project's own
// config shape is free to change as long as the properties it guarantees
// hold. This keeps `archstrict.config.ts` a one-import file that works
// whether or not archstrict is ever published, and matches spike 4's own
// fixture (a self-contained `Config<ModuleName>` beside the generated
// file, not a package import).
//
// As of the CLI cutover, declaredModules is the only thing init writes
// for module scope - not modules/kinds (index.ts-presence discovery is
// gone; a barrel index.ts was measured NOT to be evidence of an enforced
// boundary in NestJS's or Drizzle's own real code). init still does the
// SAME discovery walk it always did (buildModuleGraph's own v0 path) to
// find the directories to declare - discovery survives as init's own
// one-time suggestion, never as a runtime assumption `check`/`todo` make.
import { existsSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildModuleGraph } from "../module-graph.js";
import { SCHEMA_VERSION } from "../config.js";

export type InitResult = {
  configPath: string;
  generatedPath: string;
  configWritten: boolean; // false when archstrict.config.ts already existed and was left alone
  moduleNames: string[];
  seededExcludeDirs: string[]; // real top-level noise directories found and excluded (empty when none, or when configWritten is false)
};

// Deliberately narrow: a name must be near-universally non-source across
// ordinary TypeScript projects, not merely something one specific project
// happened to use (e.g. docs/, migrations/, or this project's own
// plugin/skills directories are real source in some real projects, so they
// stay out). init only ever excludes a name from this list when it finds a
// real top-level directory of that name on disk - never blindly.
const NOISE_DIR_CANDIDATES = [
  "test",
  "tests",
  "example",
  "examples",
  "spike",
  "dist",
  "build",
  "coverage",
  "fixtures",
  "e2e",
];

function findNoiseDirs(projectRoot: string): string[] {
  return NOISE_DIR_CANDIDATES.filter((name) => {
    const candidate = join(projectRoot, name);
    return existsSync(candidate) && statSync(candidate).isDirectory();
  });
}

// The flat preset, the only one init writes: every module under the glob
// is the same kind, checked for a public surface and cycles only.
// `because` is mandatory even for a shipped preset's own rule.
const FLAT_BECAUSE =
  "flat preset: every module under the glob is one kind, checked for its public surface and cycles";

// The public-surface file name is not fixed by the tool — a project's own
// config names it. init does not try to detect an existing convention
// (a repository that already used a different name for this purpose would
// need to say so itself); it always writes this literal default, and a
// project free to rename its own surface file edits `surface` afterward.
const DEFAULT_SURFACE = "index.ts";

function generatedFileContents(moduleNames: string[]): string {
  const union = moduleNames.length > 0 ? moduleNames.map((n) => JSON.stringify(n)).join(" | ") : "never";
  return `// Generated by archstrict init. Do not edit.
// A stale name here means a module was added, removed, or renamed since
// the last init; run init again to regenerate.
export type ModuleName = ${union};

// configPath is added by the loader, not written here - a config file
// cannot know its own path.
export type Config = {
  // The schema this config was written for. ${SCHEMA_VERSION} is the only
  // value archstrict reads. Omit it and the loader treats the file as
  // schema ${SCHEMA_VERSION}.
  schemaVersion?: ${SCHEMA_VERSION};
  surface?: string;
  deprecated?: readonly {
    from: ModuleName;
    to: ModuleName;
    count: number;
    because: string;
  }[];
  // Module names whose todo file may only shrink, never gain a new entry.
  // check reports any existing entry in one of these modules' todo as a
  // violation in its own right.
  strict?: readonly ModuleName[];
  // A specific known cycle (naming any two modules in it, in either
  // order) exempted from rule 2 - an entry naming a pair no longer in any
  // real cycle is itself flagged (stale-cycle-exception).
  ignoredCycles?: readonly (readonly [string, string])[];
  // An analysis boundary narrower than the whole project - not yet read
  // by any rule or verb (declared here for forward compatibility; wiring
  // it in is separate, later work).
  scope?: string;
  // Glob patterns kept out of analysis entirely - not a member of any
  // module, not a source of edges, not a target either. init writes one
  // default: this project's own root-level files (archstrict.config.ts,
  // archstrict.types.ts) are never module content.
  exclude?: readonly string[];
  // glob -> tags, most-specific-glob-wins. Independent of declaredModules
  // below - tags classify any file; declaredModules says which files form
  // an enforced module boundary.
  classify?: readonly { glob: string; tags: readonly string[] }[];
  // Ambient tagging by directory-name segment: the nearest path segment
  // matching one of \`names\`, walking from the file outward, becomes
  // \`\${tagNamespace}:\${name}\`. Independent of \`classify\` above - a file
  // can carry tags from both mechanisms at once.
  classifyByDirectoryName?: {
    tagNamespace: string;
    names: readonly string[];
  };
  // Declared modules - the source of truth for module boundaries.
  // \`surface\` may itself be a glob (a module's public surface can be
  // more than one file).
  declaredModules: readonly {
    name: ModuleName;
    glob: string;
    // A single glob, or several - a real package can publish more than
    // one real, differently-shaped public entry point at once. Optional:
    // when absent, a real package.json's own exports map at this
    // module's own root is derived back to source instead, falling back
    // to this project's own top-level surface default otherwise.
    surface?: string | readonly string[];
    // Rule 1's own "friend" exception: \`file\` (relative to this module,
    // may itself be a glob) is public to exactly the importers \`from\`
    // (a project-relative glob) matches, private to everyone else -
    // unlike \`surface\`, which is public to every importer equally.
    friends?: readonly { file: string; from: string; because: string }[];
  }[];
  // A directory that must hold no code at all (archspec's own
  // "empty component" idea) - a violation is any file matching the glob.
  mustBeEmpty?: readonly { glob: string; because: string }[];
  // The constraint engine: allowDeny/order/point rules over classify
  // tags, generalizing the fixed module vocabulary above. \`allowDeny\`'s
  // own \`exceptions\`: a from/to glob or tag-predicate pair that overrides
  // that rule either way for one specific edge - \`point\` has no
  // exceptions of its own, its from/to predicates already being as
  // explicit as a rule gets.
  edges?: {
    allowDeny?: readonly {
      source: string;
      targetNamespace: string;
      allow?: readonly string[];
      deny?: readonly string[];
      exceptions?: readonly { from: string; to: string; because: string }[];
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
    order?: readonly {
      tagNamespace: string;
      within?: string;
      sequence: Record<string, readonly string[]>;
      direction: "downward-only";
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
    point?: readonly {
      from: string | { tags: readonly string[]; exclude?: { tags: readonly string[] } };
      to: string | { tags: readonly string[] };
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
  };
  because: string;
};
`;
}

function configFileContents(
  modulesGlob: string,
  surface: string,
  moduleNames: string[],
  noiseDirs: string[],
): string {
  const modulesRoot = modulesGlob.slice(0, -1); // "src/*" -> "src/"
  const declaredModulesEntries = moduleNames
    .map(
      (name) =>
        `    { name: ${JSON.stringify(name)}, glob: ${JSON.stringify(`${modulesRoot}${name}/**`)}, surface: ${JSON.stringify(surface)} },`,
    )
    .join("\n");

  const excludeEntries = ["*.ts", ...noiseDirs.map((name) => `${name}/**`)];
  const excludeLine = `exclude: ${JSON.stringify(excludeEntries)},`;
  const excludeComment =
    noiseDirs.length > 0
      ? `\n  // Auto-excluded: found on disk as real top-level directories and treated as\n  // common non-module noise (${noiseDirs.join(", ")}) - remove an entry below if\n  // one of them IS real module content.`
      : "";

  return `import type { Config } from "./archstrict.types.js";

// Public surface convention: a module's ${surface} (named by \`surface\`
// below) is the only file other modules may import from it. An import
// that reaches any other file inside a module is a violation. A module
// with no ${surface} is entirely private - every import into it violates.
export default {
  schemaVersion: ${SCHEMA_VERSION},
  surface: ${JSON.stringify(surface)},
  // Root-level files (this config, the generated union type) are never
  // module content - kept out of analysis entirely, not just uncounted.${excludeComment}
  ${excludeLine}
  classify: [{ glob: ${JSON.stringify(`${modulesRoot}**`)}, tags: ["kind:flat"] }],
  declaredModules: [
${declaredModulesEntries}
  ],
  because: ${JSON.stringify(FLAT_BECAUSE)},
} satisfies Config;
`;
}

export function init(projectRoot: string, modulesGlob = "src/*", surface = DEFAULT_SURFACE): InitResult {
  const graph = buildModuleGraph({ projectRoot, modulesGlob, surface });
  const moduleNames = [...graph.modules.keys()].sort();

  const generatedPath = join(projectRoot, "archstrict.types.ts");
  writeFileSync(generatedPath, generatedFileContents(moduleNames));

  const configPath = join(projectRoot, "archstrict.config.ts");
  const configWritten = !existsSync(configPath);
  const seededExcludeDirs = configWritten ? findNoiseDirs(projectRoot) : [];
  if (configWritten) {
    writeFileSync(configPath, configFileContents(modulesGlob, surface, moduleNames, seededExcludeDirs));
  }

  return { configPath, generatedPath, configWritten, moduleNames, seededExcludeDirs };
}
